import { PGlite } from '@electric-sql/pglite';
import { readFileSync } from 'node:fs';
import { pathToFileURL, fileURLToPath } from 'node:url';

export const REPO = fileURLToPath(new URL('../../', import.meta.url)).replace(/[\\/]$/, '');
const isMain = import.meta.url === pathToFileURL(process.argv[1]).href;
let pass = 0, fail = 0;
const ok = (name, cond, extra = '') => {
  if (cond) { pass++; console.log('  PASS', name); }
  else { fail++; console.log('  FAIL', name, extra); }
};

export const U = {
  admin:   '00000000-0000-0000-0000-00000000000a',
  vice:    '00000000-0000-0000-0000-00000000000b',
  teacher: '00000000-0000-0000-0000-00000000000c',
};
export const Y_ACTIVE = '10000000-0000-0000-0000-000000000001';
export const Y_ARCH   = '10000000-0000-0000-0000-000000000002';

// Baseline mirrors the live project (columns, FKs, policies, grants read from production on 2026-10-06).
export async function buildBaseline(db) {
await db.exec(`
CREATE ROLE anon NOLOGIN; CREATE ROLE authenticated NOLOGIN; CREATE ROLE service_role NOLOGIN BYPASSRLS;
CREATE SCHEMA auth;
GRANT USAGE ON SCHEMA public, auth TO anon, authenticated, service_role;
CREATE TABLE auth.users (id uuid PRIMARY KEY, email text);
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS
  $$ SELECT NULLIF(current_setting('request.jwt.claim.sub', true), '')::uuid $$;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA auth TO anon, authenticated, service_role;
INSERT INTO auth.users VALUES ('${U.admin}','a@x'),('${U.vice}','v@x'),('${U.teacher}','t@x');

CREATE TABLE public.profiles (id uuid PRIMARY KEY REFERENCES auth.users(id), name text NOT NULL,
  role text NOT NULL CHECK (role IN ('admin','vice','teacher')));
INSERT INTO public.profiles VALUES ('${U.admin}','القائدة','admin'),('${U.vice}','الوكيلة','vice'),
  ('${U.teacher}','حساب المعلمات','teacher');
CREATE FUNCTION public.current_app_role() RETURNS text LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS
  $$ SELECT p.role FROM public.profiles p WHERE p.id = auth.uid() $$;
CREATE FUNCTION public.is_admin() RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS
  $$ SELECT EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role='admin') $$;
CREATE FUNCTION public.is_staff() RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS
  $$ SELECT EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND p.role IN ('admin','vice')) $$;

CREATE TABLE public.school_years (id uuid PRIMARY KEY, name text, status text, is_active boolean, is_archived boolean);
INSERT INTO public.school_years VALUES ('${Y_ACTIVE}','1447','active',true,false),('${Y_ARCH}','1446','archived',false,true);
CREATE FUNCTION public.school_year_allows_write(p_year_id uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS
  $$ SELECT EXISTS (SELECT 1 FROM public.school_years sy WHERE sy.id=p_year_id AND sy.is_active AND NOT sy.is_archived AND sy.status='active') $$;
CREATE FUNCTION public.school_year_is_active(p uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS
  $$ SELECT public.school_year_allows_write(p) $$;
CREATE FUNCTION public.school_year_allows_read(p uuid) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path='' AS
  $$ SELECT CASE WHEN p IS NULL THEN false
     WHEN public.is_staff() THEN EXISTS (SELECT 1 FROM public.school_years sy WHERE sy.id=p)
     WHEN public.current_app_role()='teacher' THEN public.school_year_allows_write(p)
     ELSE false END $$;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO anon, authenticated, service_role;

CREATE TABLE public.programs (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name text, resp text,
  progress integer DEFAULT 0, school_year_id uuid REFERENCES public.school_years(id));
CREATE TABLE public.program_indicators (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  program_id bigint REFERENCES public.programs(id) ON DELETE CASCADE, indicator_text text,
  is_completed boolean DEFAULT false, created_at timestamp DEFAULT now());
CREATE TABLE public.evidence_requirements (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  indicator_id bigint NOT NULL REFERENCES public.program_indicators(id) ON DELETE CASCADE, name text NOT NULL,
  sort_order integer DEFAULT 0, is_approved boolean NOT NULL DEFAULT false, approved_by uuid, approved_at timestamptz,
  created_by uuid, created_at timestamptz DEFAULT now(), updated_at timestamptz DEFAULT now());
CREATE TABLE public.evidences (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, title text,
  program_id bigint, initiative_id bigint, link text, evidence_link text, file_url text, notes text,
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL, created_at timestamptz DEFAULT now(), type text,
  initiative_label text, person text, date date, file_data text, upload_date date,
  indicator_id bigint REFERENCES public.program_indicators(id) ON DELETE SET NULL,
  school_year_id uuid REFERENCES public.school_years(id) ON DELETE RESTRICT, file_name text, file_size bigint,
  requirement_id uuid REFERENCES public.evidence_requirements(id) ON DELETE SET NULL);

ALTER TABLE public.programs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.program_indicators ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.evidence_requirements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.evidences ENABLE ROW LEVEL SECURITY;

CREATE POLICY programs_select ON public.programs FOR SELECT TO authenticated
  USING (public.current_app_role() IN ('admin','vice','teacher'));
CREATE POLICY programs_update ON public.programs FOR UPDATE TO authenticated
  USING (public.current_app_role() IN ('admin','vice') AND public.school_year_allows_write(school_year_id))
  WITH CHECK (public.current_app_role() IN ('admin','vice') AND public.school_year_allows_write(school_year_id));
CREATE POLICY programs_delete ON public.programs FOR DELETE TO authenticated
  USING (public.is_admin() AND public.school_year_allows_write(school_year_id));

CREATE POLICY indicators_select ON public.program_indicators FOR SELECT TO authenticated
  USING (public.current_app_role() IN ('admin','vice','teacher') AND EXISTS (SELECT 1 FROM public.programs pr
    WHERE pr.id = program_indicators.program_id AND public.school_year_allows_read(pr.school_year_id)));
CREATE POLICY indicators_insert ON public.program_indicators FOR INSERT TO authenticated
  WITH CHECK (public.current_app_role() IN ('admin','vice') AND EXISTS (SELECT 1 FROM public.programs pr
    WHERE pr.id = program_indicators.program_id AND public.school_year_allows_write(pr.school_year_id)));
CREATE POLICY indicators_update ON public.program_indicators FOR UPDATE TO authenticated
  USING (public.current_app_role() IN ('admin','vice') AND EXISTS (SELECT 1 FROM public.programs pr
    WHERE pr.id = program_indicators.program_id AND public.school_year_allows_write(pr.school_year_id)))
  WITH CHECK (public.current_app_role() IN ('admin','vice') AND EXISTS (SELECT 1 FROM public.programs pr
    WHERE pr.id = program_indicators.program_id AND public.school_year_allows_write(pr.school_year_id)));
CREATE POLICY indicators_delete ON public.program_indicators FOR DELETE TO authenticated
  USING (public.is_admin() AND EXISTS (SELECT 1 FROM public.programs pr
    WHERE pr.id = program_indicators.program_id AND public.school_year_allows_write(pr.school_year_id)));

CREATE POLICY evidence_requirements_select ON public.evidence_requirements FOR SELECT TO authenticated
  USING (public.current_app_role() IN ('admin','vice','teacher') AND EXISTS (SELECT 1 FROM public.program_indicators pi
    JOIN public.programs pr ON pr.id = pi.program_id
    WHERE pi.id = evidence_requirements.indicator_id AND public.school_year_allows_read(pr.school_year_id)));
CREATE POLICY evidence_requirements_insert ON public.evidence_requirements FOR INSERT TO authenticated
  WITH CHECK (public.current_app_role() IN ('admin','vice') AND EXISTS (SELECT 1 FROM public.program_indicators pi
    JOIN public.programs pr ON pr.id = pi.program_id
    WHERE pi.id = evidence_requirements.indicator_id AND public.school_year_allows_write(pr.school_year_id)));
CREATE POLICY evidence_requirements_delete ON public.evidence_requirements FOR DELETE TO authenticated
  USING (public.is_admin() AND EXISTS (SELECT 1 FROM public.program_indicators pi
    JOIN public.programs pr ON pr.id = pi.program_id
    WHERE pi.id = evidence_requirements.indicator_id AND public.school_year_allows_write(pr.school_year_id)));

CREATE POLICY evidences_select ON public.evidences FOR SELECT TO authenticated
  USING (public.current_app_role() IN ('admin','vice','teacher') AND public.school_year_allows_read(school_year_id));
CREATE POLICY evidences_insert ON public.evidences FOR INSERT TO authenticated
  WITH CHECK ((public.current_app_role() IN ('admin','vice') AND public.school_year_allows_write(school_year_id) AND created_by = auth.uid())
    OR (public.current_app_role() = 'teacher' AND public.school_year_is_active(school_year_id) AND created_by = auth.uid()));
CREATE POLICY evidences_update ON public.evidences FOR UPDATE TO authenticated
  USING (public.current_app_role() IN ('admin','vice') AND public.school_year_allows_write(school_year_id))
  WITH CHECK (public.current_app_role() IN ('admin','vice') AND public.school_year_allows_write(school_year_id));
CREATE POLICY evidences_delete ON public.evidences FOR DELETE TO authenticated
  USING (public.is_admin() AND public.school_year_allows_write(school_year_id));

-- production grants: authenticated = arwdDxtm on these tables
GRANT ALL ON public.programs, public.program_indicators, public.evidence_requirements, public.evidences TO authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA public TO service_role;
`);
// applied on production (platform_migration_history: phase_evidence_multi_attachments_review_v1)
await db.exec(readFileSync(`${REPO}/sql/phase_evidence_multi_attachments_review.sql`, 'utf8'));
}

export function makeHelpers(db) {
  async function as(role, fn) {
    await db.exec(`RESET ROLE;`);
    const pgRole = role === 'anon' ? 'anon' : 'authenticated';
    await db.query(`SELECT set_config('request.jwt.claim.sub', $1, false)`, [role === 'anon' ? '' : U[role]]);
    await db.exec(`SET ROLE ${pgRole};`);
    try { return await fn(); } finally { await db.exec(`RESET ROLE;`); }
  }
  async function tryQ(sql, params = []) {
    try { const r = await db.query(sql, params); return { rows: r.rows, affected: r.affectedRows ?? 0 }; }
    catch (e) { return { error: e.message }; }
  }
  return { as, tryQ };
}

export const MIGRATION = 'phase_indicator_delete_guard.sql';
export const applyMigration = (db) => db.exec(readFileSync(`${REPO}/sql/${MIGRATION}`, 'utf8'));

if (isMain) {
const db = new PGlite();
await buildBaseline(db);
const { as, tryQ } = makeHelpers(db);
const one = async (sql, p = []) => (await db.query(sql, p)).rows[0];
const exists = async (id) => !!(await one(`SELECT 1 x FROM public.program_indicators WHERE id=$1`, [id]));

// Fixture: one active-year program and one archived-year program.
await db.exec(`
INSERT INTO public.programs (id, name, school_year_id) VALUES (1, 'برنامج نشط', '${Y_ACTIVE}'), (2, 'برنامج مؤرشف', '${Y_ARCH}');
INSERT INTO public.program_indicators (id, program_id, indicator_text) VALUES
  (10, 1, 'فارغ للقائدة'), (11, 1, 'فارغ للوكيلة'), (12, 1, 'فارغ للمعلمات'),
  (13, 1, 'له شاهد مطلوب فقط'), (14, 1, 'له مرفق بلا اسم'), (15, 1, 'له مرفق بملاحظة'),
  (16, 2, 'فارغ في سنة مؤرشفة'), (17, 1, 'فارغ للزائر');
INSERT INTO public.evidence_requirements (id, indicator_id, name) VALUES
  ('20000000-0000-0000-0000-000000000013', 13, 'تقارير'),
  ('20000000-0000-0000-0000-000000000015', 15, 'تقارير');
INSERT INTO public.evidences (title, program_id, indicator_id, requirement_id, link, notes, school_year_id, created_by) VALUES
  ('شاهد عام', 1, 14, NULL, 'https://drive.google.com/a', NULL, '${Y_ACTIVE}', '${U.vice}'),
  ('تقارير', 1, 15, '20000000-0000-0000-0000-000000000015', 'https://drive.google.com/b', 'ملاحظة مهمة', '${Y_ACTIVE}', '${U.teacher}');
`);
const snap = async () => JSON.stringify({
  er: (await db.query(`SELECT * FROM public.evidence_requirements ORDER BY id`)).rows,
  ev: (await db.query(`SELECT * FROM public.evidences ORDER BY id`)).rows,
});
const policiesOutside = async () => JSON.stringify((await db.query(`SELECT tablename, policyname, cmd, qual, with_check FROM pg_policies
  WHERE NOT (tablename='program_indicators' AND policyname='indicators_delete') ORDER BY 1,2`)).rows);
const dataBefore = await snap();
const polBefore = await policiesOutside();

console.log('\n== Before migration: vice cannot delete (existing rule) ==');
await as('vice', async () => {
  const r = await tryQ(`DELETE FROM public.program_indicators WHERE id=11`);
  ok('vice delete affects 0 rows before migration', !r.error && r.affected === 0, JSON.stringify(r));
});

console.log('\n== Apply migration (twice: re-runnable) ==');
try { await applyMigration(db); ok('migration applied', true); } catch (e) { ok('migration applied', false, e.message); }
try { await applyMigration(db); ok('migration re-run is idempotent', true); } catch (e) { ok('migration re-run is idempotent', false, e.message); }
ok('no data rows changed by migration', dataBefore === await snap());
ok('no other policy changed', polBefore === await policiesOutside());
ok('migration recorded once', (await one(`SELECT count(*)::int c FROM public.platform_migration_history WHERE migration_key='phase_indicator_delete_guard_v1'`)).c === 1);

console.log('\n== Unlinked indicators ==');
await as('admin', async () => {
  const r = await tryQ(`DELETE FROM public.program_indicators WHERE id=10 RETURNING id`);
  ok('leader deletes unlinked indicator', !r.error && r.rows.length === 1, JSON.stringify(r));
});
await as('vice', async () => {
  const r = await tryQ(`DELETE FROM public.program_indicators WHERE id=11 RETURNING id`);
  ok('vice deletes unlinked indicator', !r.error && r.rows.length === 1, JSON.stringify(r));
  const a = await tryQ(`DELETE FROM public.program_indicators WHERE id=16 RETURNING id`);
  ok('vice cannot delete in archived year (0 rows)', !a.error && a.rows.length === 0, JSON.stringify(a));
});
ok('archived-year indicator still exists', await exists(16));
await as('teacher', async () => {
  let r = await tryQ(`DELETE FROM public.program_indicators WHERE id=12 RETURNING id`);
  ok('teacher direct DELETE by id → 0 rows', !r.error && r.rows.length === 0, JSON.stringify(r));
  r = await tryQ(`DELETE FROM public.program_indicators RETURNING id`);
  ok('teacher DELETE without filter → 0 rows', !r.error && r.rows.length === 0, JSON.stringify(r));
  r = await tryQ(`TRUNCATE public.program_indicators`);
  ok('teacher TRUNCATE denied', !!r.error && /permission denied/.test(r.error), JSON.stringify(r));
  r = await tryQ(`SELECT count(*)::int c FROM public.program_indicators`);
  ok('teacher can still read indicators', !r.error && r.rows[0].c > 0, JSON.stringify(r));
});
ok('teacher target indicator still exists', await exists(12));
await as('anon', async () => {
  const r = await tryQ(`DELETE FROM public.program_indicators WHERE id=17`);
  ok('anon delete denied', !!r.error || r.affected === 0, JSON.stringify(r));
});
ok('anon target indicator still exists', await exists(17));

console.log('\n== Linked indicators are refused (no automatic data loss) ==');
for (const role of ['admin', 'vice']) {
  await as(role, async () => {
    let r = await tryQ(`DELETE FROM public.program_indicators WHERE id=13`);
    ok(`${role}: indicator with requirement refused`, !!r.error && r.error.includes('لا يمكن حذف المؤشر') && r.error.includes('1 شاهد مطلوب'), JSON.stringify(r));
    r = await tryQ(`DELETE FROM public.program_indicators WHERE id=14`);
    ok(`${role}: indicator with attachment (no requirement) refused`, !!r.error && r.error.includes('1 مرفق'), JSON.stringify(r));
    r = await tryQ(`DELETE FROM public.program_indicators WHERE id=15`);
    ok(`${role}: indicator with noted attachment refused`, !!r.error && r.error.includes('1 ملاحظة'), JSON.stringify(r));
  });
}
ok('linked indicators still exist', await exists(13) && await exists(14) && await exists(15));
ok('requirements, attachments and notes untouched', dataBefore === await snap());

console.log('\n== Program delete keeps its existing cascade ==');
await db.exec(`INSERT INTO public.programs (id, name, school_year_id) VALUES (3, 'برنامج للحذف', '${Y_ACTIVE}');
  INSERT INTO public.program_indicators (id, program_id, indicator_text) VALUES (30, 3, 'مؤشر');
  INSERT INTO public.evidence_requirements (id, indicator_id, name) VALUES ('20000000-0000-0000-0000-000000000030', 30, 'اسم');`);
await as('admin', async () => {
  const r = await tryQ(`DELETE FROM public.programs WHERE id=3 RETURNING id`);
  ok('leader deletes program (cascade unchanged)', !r.error && r.rows.length === 1, JSON.stringify(r));
});
ok('program indicators cascaded as before', !(await exists(30)));

console.log('\n== Notes stay readable to authorized roles ==');
for (const role of ['admin', 'vice', 'teacher']) {
  await as(role, async () => {
    const r = await tryQ(`SELECT notes, requirement_id FROM public.evidences WHERE notes IS NOT NULL`);
    ok(`${role} reads the note with its requirement id`, !r.error && r.rows.length === 1
      && r.rows[0].requirement_id === '20000000-0000-0000-0000-000000000015', JSON.stringify(r));
  });
}

console.log('\n== Grants ==');
const priv = async (role, p) => (await one(`SELECT has_table_privilege($1, 'public.program_indicators', $2) v`, [role, p])).v;
ok('authenticated/anon/PUBLIC have no TRUNCATE', !(await priv('authenticated', 'TRUNCATE')) && !(await priv('anon', 'TRUNCATE')) && !(await priv('public', 'TRUNCATE')));
ok('authenticated keeps SELECT/INSERT/UPDATE/DELETE', (await priv('authenticated', 'SELECT')) && (await priv('authenticated', 'INSERT'))
  && (await priv('authenticated', 'UPDATE')) && (await priv('authenticated', 'DELETE')));
ok('service_role keeps TRUNCATE', await priv('service_role', 'TRUNCATE'));

console.log('\n== Rollback block ==');
{
  const src = readFileSync(`${REPO}/sql/${MIGRATION}`, 'utf8');
  const m = [...src.matchAll(/\/\*\s*\n(BEGIN;[\s\S]*?COMMIT;)[\s\S]*?\*\//g)];
  try { await db.exec(m[m.length - 1][1]); ok('rollback block runs', true); } catch (e) { ok('rollback block runs', false, e.message); }
  const pol = await one(`SELECT qual FROM pg_policies WHERE tablename='program_indicators' AND policyname='indicators_delete'`);
  ok('rollback restores admin-only delete policy', /is_admin\(\)/.test(pol.qual), pol.qual);
  ok('rollback kept data', dataBefore === await snap());
}

console.log(`\nRESULT: ${pass} passed, ${fail} failed`);
process.exit(fail ? 1 : 0);
}
